#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run build only when pushing to main branch
while read local_ref local_sha remote_ref remote_sha
do
  if [ "$remote_ref" = "refs/heads/main" ]; then
    echo "Running build before pushing to main..."
    npm run build || exit 1
  fi
done

exit 0
